return { -- Autocompletion
  --   'hrsh7th/nvim-cmp',
  --   event = 'InsertEnter',
  --   dependencies = {
  --     require 'plugins.luasnip',
  --     'saadparwaiz1/cmp_luasnip',
  --     'hrsh7th/cmp-nvim-lsp',
  --     'hrsh7th/cmp-path',
  --   },
  --   config = function()
  --     local cmp = require 'cmp'
  --     local luasnip = require 'luasnip'
  --     luasnip.config.setup {}
  --
  --     cmp.setup {
  --       snippet = {
  --         expand = function(args)
  --           luasnip.lsp_expand(args.body)
  --         end,
  --       },
  --       completion = { completeopt = 'menu,menuone,noinsert' },
  --
  --       mapping = cmp.mapping.preset.insert {
  --         ['<M-y>'] = cmp.mapping(function()
  --           local accept = vim.fn['copilot#Accept']
  --           local res = accept(vim.api.nvim_replace_termcodes('<Tab>', true, true, false))
  --           res = res .. '\n'
  --           vim.api.nvim_feedkeys(res, 'n', false)
  --         end),
  --
  --         ['<C-l>'] = cmp.mapping(function()
  --           local accept = vim.fn['copilot#AcceptLine']
  --           local res = accept(vim.api.nvim_replace_termcodes('<M-C-Right>', true, true, false))
  --           vim.api.nvim_feedkeys(res, 'n', false)
  --         end),
  --
  --         ['Tab'] = cmp.mapping(function()
  --           local accept = vim.fn['copilot#AcceptLine']
  --           local res = accept(vim.api.nvim_replace_termcodes('<M-C-Right>', true, true, false))
  --           vim.api.nvim_feedkeys(res, 'n', false)
  --         end),
  --       },
  --       sources = {
  --         {
  --           name = 'lazydev',
  --           -- set group index to 0 to skip loading LuaLS completions as lazydev recommends it
  --           group_index = 0,
  --         },
  --         { name = 'nvim_lsp' },
  --         { name = 'luasnip' },
  --         { name = 'path' },
  --         { name = 'render-markdown' },
  --       },
  --     }
  --   end,
}
